# Generated by Django 2.0.2 on 2018-02-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect4', '0005_auto_20180211_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
