# Generated by Django 2.0.2 on 2018-02-24 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('connect4', '0007_auto_20180223_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computerplayer',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='userplayer',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RenameField(
            model_name='player',
            old_name='loses',
            new_name='losses',
        ),
        migrations.AddField(
            model_name='player',
            name='draws',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='player',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_connect4.player_set+', to='contenttypes.ContentType'),
        ),
    ]
