# Generated by Django 2.0.2 on 2018-02-24 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect4', '0008_auto_20180224_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect4.Player'),
        ),
    ]
